#!/usr/bin/env bash
# Script to ping an IP address passed as an argument.

# Check if an argument is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
# Store the IP address from the argument
ip_address=$1
# Ping the IP address 5 times
ping -c 5 "$ip_address"
