#!/bin/bash
# Init script to manage the manage_my_process script as a daemon

case "$1" in
    start)
        echo "Starting my_process..."
        /bin/bash manage_my_process &
        echo $! > /tmp/manage_my_process.pid
        ;;
    stop)
        echo "Stopping my_process..."
        kill $(cat /tmp/manage_my_process.pid)
        rm /tmp/manage_my_process.pid
        ;;
    restart)
        echo "Restarting my_process..."
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
