#!/usr/bin/env bash
# Init script to manage the manage_my_process script as a daemon
PIDFILE=/var/run/my_process.pid
DAEMON=manage_my_process
case "$1" in
    start)
        echo "manage_my_process started"
        /bin/bash manage_my_process &
        echo $! > $PIDFILE
        ;;
    stop)
        echo "manage_my_process stopped"
        kill $(cat $PIDFILE)
        rm $PIDFILE
        ;;
    restart)
        echo "manage_my_process started restarted"
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
esac
