#!/usr/bin/env bash
# This script stops the '4-to_infinity_and_beyond' script.
pid=$(pgrep -f '4-to_infinity_and_beyond.sh')
if [ -z "$pid" ]; then
    echo "The process '4-to_infinity_and_beyond.sh' is not running."
else
    kill "$pid"
    echo "Process '4-to_infinity_and_beyond.sh' has been terminated."
fi