#!/usr/bin/env bash
# This script stops the '4-to_infinity_and_beyond' script by sending a termination signal using pkill.

# Use pkill to send the SIGTERM signal to any process that matches the full command line pattern.
pkill -f '4-to_infinity_and_beyond'