#!/usr/bin/env bash
# This script prints 'To infinity and beyond' indefinitely with a pause of 2 seconds between each print.

while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
