#!/usr/bin/env bash
# This script displays numbers from 1 to 100, substituting multiples of 3 and 5 with 'FizzBuzz',
# multiples of 3 with 'Fizz', and multiples of 5 with 'Buzz'.

for i in {1..100}; do
    # Check for multiple of 3 and 5
    if (( i % 3 == 0 && i % 5 == 0 )); then
        echo "FizzBuzz"
    # Check for multiple of 3
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    # Check for multiple of 5
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    # Default to displaying the number
    else
        echo "$i"
    fi
done
