#!/usr/bin/env bash
# Script to display all active IPv4 IPs on the machine

# Get the list of IP addresses, filter for IPv4, and then format the output to show only the IP addresses
ip -4 addr show | grep -oP 'inet \K[\d.]+' | awk '{print $1}'
